In [1]:
import numpy as np

In [2]:
import torch 



In [3]:
print(torch.cuda.is_available())

False


In [4]:
print(torch.rand(2,2))

tensor([[0.9646, 0.2626],
        [0.8303, 0.9887]])


In [5]:
#creating tensors from lists

x = torch.tensor([[0,0,1], [1,1,1],[0,0,0]])

In [6]:
x

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [7]:
#we can chnage elements by standard indexing ==> for example

x[0][0] = 5
x

tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [8]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [11]:
torch.rand(1).item()

0.5140116810798645

In [14]:
cpu_tensor = torch.rand(2)

In [15]:
cpu_tensor.device

device(type='cpu')

In [16]:
gpu_tensor = cpu_tensor.to("cuda") #no cuda!

AssertionError: Torch not compiled with CUDA enabled

#### TENSOR OPERATIONS!

In [17]:
torch.rand(2,2).max()

tensor(0.3633)

In [18]:
torch.rand(2,2).max().item()

0.912397563457489

In [19]:
#chnage type of tensor

long_tensor = torch.tensor([[0,0,1],[1,1,1], [0,0,0]])

In [20]:
long_tensor.type()

'torch.LongTensor'

In [21]:
float_tesnor = torch.tensor([[0,0,1],[1,1,1], [0,0,0]]).to(dtype=torch.float32)

In [22]:
float_tesnor.type()

'torch.FloatTensor'

In [23]:
random_tensor = torch.rand(2,2)

In [24]:
random_tensor.log2()

tensor([[-1.8360, -1.7085],
        [-0.5965, -0.0284]])

In [25]:
random_tensor.log2_()

tensor([[-1.8360, -1.7085],
        [-0.5965, -0.0284]])

In [26]:
### reshaping tensors

flat_tensor = torch.rand(784)


In [27]:
view_tensor = flat_tensor.view(1, 28, 28)

In [28]:
view_tensor.shape

torch.Size([1, 28, 28])

In [29]:
reshape_tensor = flat_tensor.reshape(1, 28, 28)

In [30]:
reshape_tensor.shape

torch.Size([1, 28, 28])

In [31]:
hwc_tensor = torch.rand(640, 480, 3)

In [34]:
chw_tensor = hwc_tensor.permute(2, 0, 1)

In [35]:
chw_tensor.shape

torch.Size([3, 640, 480])

In [ ]:
### Tensor Broadcasting

