# Using PyTorch + GPU/TPU in Google's Colab

> Colaboratory is a Google research project created to help disseminate machine learning education and research. It's a Jupyter notebook environment that requires no setup to use and runs entirely in the cloud.
> Colaboratory notebooks are stored in Google Drive and can be shared just as you would with Google Docs or Sheets. Colaboratory is free to use.
> -- https://colab.research.google.com/notebooks/welcome.ipynb

**Setup**
- Go to https://colab.research.google.com
- Create a new python 3 notebook
- Enable the GPU: "Edit -> Notebook settings -> Hardware accelerator: GPU -> Save"
- Then try the following:

```python
import torch

print(torch.__version__)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(DEVICE)
```

You should get something like this:
> 1.0.1.post2
>
> cuda

In [6]:
import IPython


In [ ]:
import torch
from IPython.core.debugger import set_trace

def f(x):
    res = x * x
    set_trace() # a way of debugging!!! OMG 
    return res

x = torch.randn(1, requires_grad=True)
y = f(x)

> <ipython-input-9-4399e31f9b35>(7)f()
      5     res = x * x
      6     set_trace() # a way of debugging!!! OMG
----> 7     return res
      8 
      9 x = torch.randn(1, requires_grad=True)

ipdb> 12
12
ipdb> x**2
tensor([1.1422], grad_fn=<PowBackward0>)
ipdb> x
tensor([1.0687], requires_grad=True)
ipdb> x/2
tensor([0.5344], grad_fn=<DivBackward0>)


# Using this Repo in Colab
You can use this repo with google colab,
but not all notebooks run without changes.
Some notebooks import from `utils.py` which is not availbale on colab.
You have to remove that line and copy and paste the required function/class into the notebook.

It's easy to use colab. Simply append the url from the notebook on github to `https://colab.research.google.com/github/`. E.g. `notebooks/pytorch_basics.ipynb` is available under:
https://colab.research.google.com/github/sotte/pytorch_tutorial/blob/master/notebooks/pytorch_basics.ipynb)